{
    parserClass="ignormies.qss.parser.QSSParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="QSS"
    psiImplClassSuffix="Impl"
    psiPackage="ignormies.qss.psi"
    psiImplPackage="ignormies.qss.psi.impl"

    elementTypeHolderClass="ignormies.qss.psi.QSSTypes"
    elementTypeClass="ignormies.qss.psi.QSSElementType"
    tokenTypeClass="ignormies.qss.psi.QSSTokenType"

    psiImplUtilClass="ignormies.qss.psi.impl.QSSPsiImplUtil"

    tokens = [
       SEMICOLON=";"
       OPEN_BRACE="{"
       CLOSE_BRACE="}"
    ]
}

file ::= style_rule*

style_rule ::= selector_list declaration_block
selector_list ::= IDENTIFIER+

declaration_block ::= OPEN_BRACE declaration_list CLOSE_BRACE
declaration_list ::= declaration (SEMICOLON declaration)*
declaration ::= property COLON EXPRESSION
property ::= IDENTIFIER



// IN PROGRESS:

//selector ::= selector_ selector*
//selector_ ::= universal_selector | type_selector | property_selector | class_selector
//              | id_selector | descendent_selector | child_selector
//
//universal_selector ::= "*"
//type_selector ::= CLASS_TYPE
//property_selector ::= type_selector property*  // TODO
//class_selector ::= "." selector_
//id_selector ::= type_selector? "#" selector_
//descendent_selector ::= type_selector selector_
//child_selector ::= type_selector ">" selector_
